import { NextResponse, type NextRequest } from "next/server";
import { cookies } from "next/headers";
import { ClientService } from "@/lib/services/client";
import { AuthenticationService } from "@/lib/services/auth";
import { ConsentService } from "@/lib/services/consent";
import { OAuth2Service } from "@/lib/services/oauth2";
import { parseScopes, isRedirectUriAllowed } from "@/lib/utils";
import { env } from "@/lib/env";
import { rateLimit } from "@/lib/redis";

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const responseType = searchParams.get("response_type");
    const clientId = searchParams.get("client_id");
    const redirectUri = searchParams.get("redirect_uri");
    const scope = searchParams.get("scope") || "";
    const state = searchParams.get("state") || "";
    const codeChallenge = searchParams.get("code_challenge");
    const codeChallengeMethod = searchParams.get("code_challenge_method") || "S256";

    // Optional: PKCE verifier can be embedded inside state payload (generated by our portal)
    // We will append it to the redirect as URL fragment so redirect_uri string-match is unchanged.
    let stateCodeVerifier: string | null = null;

    if (state) {
      try {
        const decoded = Buffer.from(state, "base64url").toString("utf8");
        const parsed = JSON.parse(decoded);
        if (parsed?.t === "pkce" && typeof parsed?.v === "string") {
          stateCodeVerifier = parsed.v;
        }
      } catch {
        // ignore invalid state payload
      }
    }

    // Rate limiting per IP: max 30 requests per minute per IP for authorize endpoint
    const ip = request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || 
               request.headers.get("x-real-ip") || 
               "127.0.0.1";
    const ipRateLimitKey = `rate_limit:authorize:ip:${ip}`;
    const ipRateCheck = await rateLimit(ipRateLimitKey, 30, 60);
    if (!ipRateCheck.success) {
      return NextResponse.json(
        { error: "slow_down", error_description: "Too many requests from this IP address. Please try again later." },
        { status: 429 }
      );
    }

    // 1. Basic parameter validation
    if (!clientId || !redirectUri || !codeChallenge) {
      return new NextResponse("Missing required parameters (client_id, redirect_uri, code_challenge)", { status: 400 });
    }

    if (responseType !== "code") {
      return NextResponse.redirect(`${redirectUri}?error=unsupported_response_type&state=${encodeURIComponent(state)}`);
    }

    // 2. Client verification
    const app = await ClientService.getApplicationByClientId(clientId);
    if (!app || app.status !== "active") {
      return new NextResponse("Unauthorized client application", { status: 400 });
    }

    // Validate redirect URI against application whitelist
    if (!isRedirectUriAllowed(app.redirectUris, redirectUri)) {
      return new NextResponse("Invalid redirect_uri", { status: 400 });
    }

    // 2b. Enforce PKCE S256 for public clients (SPA/mobile)
    if (app.isPublicClient && codeChallengeMethod !== "S256") {
      return NextResponse.redirect(
        `${redirectUri}?error=invalid_request&error_description=Public+clients+must+use+PKCE+with+S256+method&state=${encodeURIComponent(state)}`
      );
    }

    // 3. User session check
    const cookieStore = await cookies();
    const sessionId = cookieStore.get("sso_session")?.value;
    let sessionUser: any = null;

    if (sessionId) {
      const sessionCheck = await AuthenticationService.validateSession(sessionId);
      if (sessionCheck.valid && sessionCheck.session) {
        sessionUser = sessionCheck.session;
      }
    }

    // Build client URL for redirects using request origin as base,
    // but tolerate configs where NEXT_PUBLIC_APP_URL still points to localhost.
    const publicBase = env.NEXT_PUBLIC_APP_URL.replace(/\/+$/, "");
    const requestOrigin = request.nextUrl.origin;
    const resolvedBase =
      publicBase && !publicBase.includes("localhost") && !publicBase.includes("127.0.0.1")
        ? publicBase
        : requestOrigin;
    const clientUrl = `${resolvedBase}${request.nextUrl.pathname}${request.nextUrl.search}`;

    if (!sessionUser) {
      // Redirect to login page, preserving request URL for post-login return
      const loginUrl = new URL("/login", clientUrl);
      loginUrl.searchParams.set("return_to", clientUrl);
      return NextResponse.redirect(loginUrl.toString());
    }

    // 4. Consent check
    const requestedScopes = parseScopes(scope);
    let consented = await ConsentService.hasActiveConsent(sessionUser.userId, app.id, requestedScopes);

    // Auto-grant consent for built-in campus platforms
    const isBuiltInApp = [
      "siakad-platform",
      "lms-platform",
      "pmb-platform",
      "keuangan-platform",
      "hris-platform",
      "bank-konten-platform",
    ].includes(app.clientId);

    if (!consented && isBuiltInApp) {
      await ConsentService.grantConsent(sessionUser.userId, app.id, requestedScopes);
      consented = true;
    }

    if (!consented) {
      // Redirect to consent screen for external apps
      const consentUrl = new URL("/oauth/consent", clientUrl);
      consentUrl.searchParams.set("return_to", clientUrl);
      return NextResponse.redirect(consentUrl.toString());
    }

    // 5. Success: Create authorization code
    try {
      const { code } = await OAuth2Service.createAuthorizationCode({
        userId: sessionUser.userId,
        applicationId: app.id,
        redirectUri,
        scope,
        codeChallenge,
        codeChallengeMethod,
      });

      const redirectUrl = new URL(redirectUri);
      redirectUrl.searchParams.set("code", code);
      if (state) {
        redirectUrl.searchParams.set("state", state);
      }

      // Append code_verifier into fragment (not part of redirect_uri sent to server)
      if (stateCodeVerifier) {
        const fragment = `code_verifier=${encodeURIComponent(stateCodeVerifier)}`;
        // Preserve any existing fragment
        const existing = redirectUrl.hash ? redirectUrl.hash.replace(/^#/, "") : "";
        redirectUrl.hash = existing ? `${existing}&${fragment}` : fragment;
      }

      return NextResponse.redirect(redirectUrl.toString());
    } catch (err: any) {
      console.error("Error creating authorization code:", err);
      return NextResponse.redirect(`${redirectUri}?error=server_error&state=${encodeURIComponent(state)}`);
    }
  } catch (globalError: any) {
    if (globalError.message === "NEXT_REDIRECT" || globalError.digest?.startsWith("NEXT_REDIRECT")) {
      throw globalError;
    }
    console.error("SSO Auth error:", globalError);
    return NextResponse.json({ error: globalError.message, stack: globalError.stack }, { status: 500 });
  }
}
export const dynamic = "force-dynamic";
